name: Issue Assignment

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: 'Get repository collaborators'
        id: get-collaborators
        run: |
          COLLABORATORS=$(gh api repos/${{ github.repository }}/collaborators --jq 'map(.login) | map(select(. != "hellices")) | join(", ")')
          echo "COLLABORATORS=${COLLABORATORS}" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Check COLLABORATORS Value'
        run: echo "COLLABORATORS=${{ env.COLLABORATORS }}"

      - name: 'Auto-assign Issue'
        uses: pozil/auto-assign-issue@v2.2.0
        with:
          assignees: kyungjunleeme, Jake-huen, ParkGyeongTae, dpwns523, juanxiu, seulgit02, jang-namu, na3150, chaewonni, falconlee236, 97tkddnjs
          numOfAssignee: 2
          allowSelfAssign: false
  
